### ISSUE TITLE
It does not work spigot-1.16.5

### ISSUE THREAD

**Issue by Res83** [MithrandirCraft/RPGBookshelves#1]
It does not work I have activated the permissions and I can be the owner but it does not work either I am using groupmanager and I put the permissions rpgbookshelf.store and rpgbookshelf.read

**Comment by MithrandirCraft** [comment]
Any errors?
What exactly do you expect to happen, and what is it that you see?

**Comment by Res83** [comment]
> ¿Algún error?
> ¿Qué esperas que suceda exactamente y qué es lo que ves?

I hope I can touch the library with the right and that it opens and I can save a book or read a saved book but this does not happen or in OP mode it works I am using Spigot 1.65.5
